### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [picguard/picguard#271]
to continue from https://forum.f-droid.org/t/flutter-app-not-reproducible/27462

this recipe **metadata/com.kjxbyz.picguard.yml**
```
Categories:
  - Graphics
  - Multimedia
License: MIT
AuthorName: kjxbyz
AuthorEmail: kjxbyz888@outlook.com
AuthorWebSite: https://kjxbyz.com
WebSite: https://picguard.app
SourceCode: https://github.com/picguard/picguard
IssueTracker: https://github.com/picguard/picguard/issues
Translation: https://crowdin.com/project/picguard
Changelog: https://github.com/picguard/picguard/blob/HEAD/CHANGELOG.md
Donate: https://buymeacoffee.com/wangying

AutoName: PicGuard

RepoType: git
Repo: https://github.com/picguard/picguard.git

Builds:
  - versionName: 1.0.6
    versionCode: 427
    commit: d8c730f645851e8cdcb8b0c9f6ccc232ccad789c
    sudo:
      - mkdir -p /home/runner
      - chown vagrant /home/runner
    output: build/app/outputs/apk/freeProduction/release/PicGuard*.apk
    binary: https://github.com/picguard/picguard/releases/download/v%v+%c/PicGuard_%v+%c-free.apk
    srclibs:
      - flutter@stable
    rm:
      - ios
      - macos
      - linux
      - windows
      - web
    prebuild:
      - export repo=/home/runner/work/picguard
      - mkdir -p $repo
      - cd ..
      - mv com.kjxbyz.picguard $repo/picguard
      - pushd $repo/picguard
      - version=$(sed -n -E "s/.*flutter-version:\ '(.*)'/\1/p" .github/workflows/release.yml
        | head -n1)
      - '[[ $version ]] || exit 1'
      - git -C $$flutter$$ checkout -f $version
      - export PUB_CACHE=$(pwd)/.pub-cache
      - $$flutter$$/bin/flutter config --no-analytics
      - $$flutter$$/bin/flutter packages pub get
      - popd
      - mv $repo/picguard com.kjxbyz.picguard
    scandelete:
      - .pub-cache
    build:
      - export repo=/home/runner/work/picguard
      - cd ..
      - mv com.kjxbyz.picguard $repo/picguard
      - pushd $repo/picguard
      - export PUB_CACHE=$(pwd)/.pub-cache
      - $$flutter$$/bin/flutter build apk --no-tree-shake-icons --target lib/main_free.dart --flavor freeProduction
      - popd
      - mv $repo/picguard com.kjxbyz.picguard

AllowedAPKSigningKeys: fe69efc59902edfe034ad62a6ac9a1fc0ee253822b57f950dc267edb417080f7

AutoUpdateMode: Version
UpdateCheckMode: Tags .*[0-9]$
UpdateCheckData: pubspec.yaml|version:\s.+\+(\d+)|.|version:\s(.+)\+
CurrentVersion: 1.0.6
CurrentVersionCode: 427
```

builds fine and it's repro :tada: 

@kjxbyz are you still interested to add it ?

If yes, scanning your APK:
```
$ apksigtool parse --json PicGuard_1.0.6+427-free.apk | jq -r '.pairs[].value._type'
APKSignatureSchemeBlock
DependencyInfoBlock
VerityPaddingBlock
```

We find that there is a `DependencyInfoBlock` in your APK.

It's a [Signing block](https://bi-zone.medium.com/easter-egg-in-apk-files-what-is-frosting-f356aa9f4d1) added by AGP and encrypted with the Google public key so it can't be read by anyone else except Google. You can read more about it [here](https://gitlab.com/fdroid/admin/-/issues/367) and [here](https://gitlab.com/fdroid/fdroidserver/-/issues/1056).

Could you please disable it with the following code?

```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

also
```
$ apksigner verify --print-certs PicGuard_1.0.6+427-free.apk | head -n1
Signer #1 certificate DN: CN=Unknown, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown
```

can you create a proper release key that not "Unknown" and keep it safe? eg. https://f-droid.org/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html

and do rename https://github.com/picguard/picguard/tree/main/metadata/en-US/images `logo.png` to `icon.png`

We'll need a new release, tag, apk
